#!/usr/bin/env python

"""
Clean .py file generate by jupyter nbconvert
"""
from functools import reduce
import sys


def main():
    path_to_file = sys.argv[1]

    with open(path_to_file) as f:
        lines = f.readlines()

    # extra lines
    extra = [n for n, line in enumerate(lines) if line.startswith('# In')]

    # remove extra line + the two subsequent ones, also remove last line,
    # seems like jupyter adds two empty lines in the end
    to_remove = [item for sublist in [[e, e+1, e+2] for e in extra]
                 for item in sublist] + [len(lines) - 1]

    # get only clean lines
    clean_lines = [l for n, l in enumerate(lines) if n not in to_remove]
    clean_file = reduce(lambda x, y: x+y, clean_lines)

    with open(path_to_file, 'w') as f:
        f.write(clean_file)


if __name__ == '__main__':
    main()
