# script to export examples to include them in the main repo

# convert notebooks to python files
jupyter nbconvert --to script batch/*.ipynb --output-dir source/batch/

# process python files - remove extra comments generated by jupyter
for i in source/batch/*.py; do ./clean "$i"; done