# script to export examples to include them in the main repo
YASS_REPO_EXAMPLES=../yass/examples/

# convert notebooks to python files
echo 'Converting notebooks to py files...'
jupyter nbconvert --to script batch/*.ipynb --output-dir source/batch/

# process python files - remove extra comments generated by jupyter
echo 'Cleaning py files...'
for i in source/batch/*.py; do ./clean "$i"; done

# move folder to the main repo
# rm -rf ~/Desktop/test
cp -vr source/* $YASS_REPO_EXAMPLES